// Why each answer is correct. Written from general CDL knowledge, NOT yet checked
// against the official manual. The app labels every explanation as unverified.
// Keys are question ids from questions.js.
const EXPLANATIONS = {
  "air-brakes-1": "Air brakes have a brake lag: the time it takes air to travel through the lines and reach the brakes. That lag adds distance before braking even starts, which is why total stopping distance is longer than with hydraulic brakes.",
  "air-brakes-2": "Air moves through long lines more slowly than hydraulic fluid moves through its lines, so air brakes take longer to apply. The other choices do not describe the delay.",
  "air-brakes-3": "Parking brakes should be applied any time the vehicle is parked. Using them as little as possible is wrong, because they are meant for parking, not for slowing down on a hill.",
  "air-brakes-4": "The stop light switch is the switch on the brake pedal that turns on the brake lights so drivers behind you know you are slowing. It does not warn about air pressure or emergency brakes.",
  "air-brakes-5": "A fully charged air brake system is normally at about 125 psi. The air compressor keeps pumping until the system reaches that level.",
  "air-brakes-6": "Pressing and releasing the brake pedal over and over uses air from the tanks each time, so pressure drops. That loss is why repeated partial braking can lower air pressure.",
  "air-brakes-7": "On a long, steep downhill, you brake until you are about 5 mph below the posted speed, then release the brakes. Braking lower than that wastes heat and can overheat the brakes.",
  "air-brakes-8": "Using the brakes too much makes them overheat. Overheated brakes can lose their stopping power, which is called brake fade.",
  "air-brakes-9": "Overheating makes brake drums expand. Expanded drums move away from the linings, so the brakes must be applied further to stop the vehicle.",
  "air-brakes-10": "During normal driving, air pressure holds the spring brakes back, so they stay released. When the air is let out, the springs apply the brakes.",
  "air-brakes-11": "The supply pressure gauge shows how much air is in the air tanks. That is the air available to the brakes.",
  "air-brakes-12": "Modern air brake systems have three parts: service brakes, parking brakes, and emergency brakes. The spring brakes that act as emergency brakes work when air pressure drops.",
  "air-brakes-13": "In an emergency stop, you should brake hard without locking the wheels, so you can still steer and keep the vehicle in a straight line. Locked wheels can't steer.",
  "air-brakes-14": "Water in the tanks can freeze in cold weather. Frozen water can block air lines or valves and cause brake failure, so tanks must be drained.",
  "air-brakes-15": "The service brake system is the one you use every time you press the brake pedal to slow or stop the vehicle.",
  "air-brakes-16": "On a long, steep downgrade, the engine's braking effect is the main way to control speed. Air brakes are only a supplement to it.",
  "air-brakes-17": "The alcohol evaporator puts alcohol into the air to keep moisture from freezing in the valves. If its alcohol level is low, moisture can freeze and cause brake failure.",
  "air-brakes-18": "The S-cam is the part that pushes the brake shoes out against the inside of the brake drum when the brakes are applied. It is the most common brake mechanism on heavy vehicles.",
  "air-brakes-19": "This is the leakage limit for a straight truck or bus with the engine off and the brakes released. Leakage above this rate means there is a problem in the system that must be fixed.",
  "air-brakes-20": "The air compressor stops pumping when the tanks reach about 125 psi. The governor controls that cut-out point.",
  "air-brakes-21": "Emergency braking means braking as hard as you can, releasing when the wheels lock, and braking again as they start to roll. This keeps you steering while stopping as quickly as possible.",
  "air-brakes-22": "A parking brake must be held by something that cannot leak away. Spring pressure holds the spring brakes, and it does not leak like air or fluid can.",
  "air-brakes-23": "Brakes are fading when you have to push harder on the pedal to get the same slowing effect, usually from overheating on a downgrade.",
  "air-brakes-24": "With the engine off and brakes on, a straight truck or bus should not lose more than 3 psi in one minute. More leakage points to a problem in the system.",
  "air-brakes-25": "Cracks in a brake drum that are longer than one half of the width of the friction area make the drum unsafe. A drum with a crack that long must not be driven.",
  "air-brakes-26": "At 55 mph a heavy vehicle needs far more than 300 feet to stop under ideal conditions. That includes the brake lag distance plus the actual braking distance.",
  "air-brakes-27": "When you press the brakes, the brake shoes or linings are pushed against the brake drum or disc. The friction between them slows the wheels.",
  "air-brakes-28": "Without automatic drains, you should drain the tanks at the end of each day of driving. That removes water and oil before they can freeze or build up.",
  "air-brakes-29": "Spring brakes are applied by spring force, not the pedal. Pushing the brake pedal does not release spring brakes, so you never push the pedal to release them.",
  "air-brakes-30": "Parking brakes should not be used to brake the vehicle hard. Using them that way can damage them and cause a skid, so the choice saying to brake hard with them is not proper.",
  "air-brakes-31": "A dual air system has two separate circuits. If one loses pressure, the brakes on that circuit do not work, so either the front or the rear brakes are not fully operational.",
  "air-brakes-32": "The S-cam drum brake is the most common foundation brake on heavy vehicles. It is the type the other choices do not describe.",
  "air-brakes-33": "Every air brake vehicle must have a supply pressure gauge. It shows the driver how much air is in the tanks.",
  "air-brakes-34": "A properly working dual system with minimum size tanks should build from 85 to 100 psi in about 45 seconds. If it takes longer, the system or compressor needs checking.",
  "air-brakes-35": "On a steep downgrade, you brake until your speed drops to about 5 mph below your safe speed. From a safe speed of 40 mph, that is 35 mph.",
  "air-brakes-36": "At 55 mph, brake lag adds about 32 feet before the brakes start to work. This is the time air takes to reach the brakes.",
  "air-brakes-37": "A major leak in the service line lets service air escape. The trailer emergency brakes then apply, which is their job when service air is lost.",
  "air-brakes-38": "You should use the parking brakes whenever you park, except when the brakes are very hot, such as right after coming down a steep grade. Hot brakes can be damaged by setting them.",
  "air-brakes-39": "Emergency controlled braking means applying the brakes as hard as you can without locking the wheels. That keeps you able to steer while stopping quickly.",
  "air-brakes-40": "A low air pressure warning means the brakes may soon stop working. You should stop and park safely as soon as possible.",
  "air-brakes-41": "You should use the parking brakes whenever you leave the vehicle unattended, so it cannot roll away.",
  "air-brakes-42": "Parking and emergency brakes on trucks and buses are held on by spring pressure. Spring pressure cannot leak away like air can.",
  "air-brakes-43": "To check manual slack adjusters, park on level ground, chock the wheels, and release the parking brakes. That lets the brakes move freely so the free play can be measured.",
  "air-brakes-44": "To set the parking brakes, you let the air out of the system. That lets the springs apply the brakes, so the answer is to let the air out.",
  "air-brakes-45": "To check service brakes, park on level ground, wait until normal air pressure is reached, release the parking brake, move slowly at about 5 mph, and apply the brakes firmly. This shows whether they hold properly.",
  "air-brakes-46": "If air pressure does not build up in the time it should, the pressure can drop too low while you drive. Then you may need an emergency stop.",
  "air-brakes-47": "The air compressor governor controls when air is pumped into the tanks. It turns the compressor on and off to keep pressure in a set range.",
  "air-brakes-48": "The alcohol evaporator reduces the risk of ice forming in the valves in cold weather. It puts alcohol into the air to keep moisture from freezing.",
  "air-brakes-49": "Slack adjuster free play that is more than about one inch when pulled hard means the brakes need adjusting. Too much free play means the brakes will not apply fully.",
  "air-brakes-50": "The modulating control valve lets the driver control the spring brakes on a tractor or straight truck. It is how spring brakes are applied gradually.",
  "air-brakes-51": "The brake pedal controls how much air pressure goes to the brakes. Pressing it harder sends more air to the brake chambers.",
  "air-brakes-52": "Spring brakes come on when air pressure drops to about 20 to 30 psi. Below that, the springs apply the brakes to stop the vehicle.",
  "air-brakes-53": "You should never leave a truck unattended without applying the parking brakes and chocking the wheels, even for a short time, because the truck can roll.",
  "air-brakes-54": "To test the service brakes, brake firmly while moving forward slowly. That shows whether the brakes stop the vehicle properly.",
  "air-brakes-55": "Before driving a dual air brake system vehicle, the air pressure must be at least 100 psi. That makes sure the brakes have enough air to work.",
  "air-brakes-56": "The application pressure gauge shows how much air pressure is being applied to the brakes when you press the pedal.",
  "air-brakes-57": "The safety valve releases air automatically at about 150 psi. That protects the system from too much pressure.",
  "air-brakes-58": "ABS changes how you brake in an emergency. It keeps the wheels from locking, so you can still steer while stopping, but it does not let you drive less carefully.",
  "air-brakes-59": "In cold weather, you should check and fill the alcohol level every day when the vehicle has an alcohol evaporator. A low level can let ice form in the valves.",
  "air-brakes-60": "With dual parking control valves, a separate tank can balance the service brakes when you are parked. It does not make the parking brake last longer.",
  "air-brakes-61": "If a low air pressure warning comes on for one system, you should bring the vehicle to a safe stop and continue only after the system is fixed. Driving on one weak system is not safe.",
  "air-brakes-62": "For combination vehicles with the engine off and brakes on, the leakage rate should be less than 4 psi per minute. More leakage means the system needs repair.",
  "air-brakes-63": "The low air pressure warning must come on before the service tank pressure falls below 60 psi. That gives the driver time to stop before the brakes lose their power.",
  "air-brakes-64": "Spring brake power depends on the service brakes being properly adjusted, because the adjustment affects how the brakes work together. If they are out of adjustment, the braking is reduced.",
  "combination-vehicles-1": "If the air lines are crossed, the trailer's emergency line gets service air. A trailer with no spring brakes can then roll and be driven, but it has no trailer brakes working.",
  "combination-vehicles-2": "The earliest sign of a trailer skid is seen in the mirrors, as the trailer swings out of line. You see it before you feel it in the cab.",
  "combination-vehicles-3": "Trailers made before 1975 often did not have spring brakes. Spring brakes are the emergency brakes that come on when air is lost.",
  "combination-vehicles-4": "To test the connection, pull gently forward in low gear against the locked trailer brakes, then look at the connection. If it is secure, the trailer will not pull free.",
  "combination-vehicles-5": "When a turn would take you into another lane, turn wide as you complete the turn, so the trailer stays in your own lane. Turning wide before you start puts the trailer into the other lane.",
  "combination-vehicles-6": "Losing air in the emergency line causes the trailer's emergency brakes to come on. That is the safety purpose of the emergency line.",
  "combination-vehicles-7": "The glad hand seals should be pressed together at a 90 degree angle, so the connection seals properly.",
  "combination-vehicles-8": "A combination vehicle has more parts to inspect than a straight truck or bus, because it includes the trailer, its air lines, and its coupling.",
  "combination-vehicles-9": "After coupling, there should be no space between the upper and lower fifth wheel. Any gap means the coupling is not secure.",
  "combination-vehicles-10": "With the engine off and brakes off, a combination vehicle should not lose more than 3 psi per minute. More leakage points to a problem.",
  "combination-vehicles-11": "If only the service line comes apart and the emergency line stays connected, the trailer's emergency brakes stay off. Nothing happens until you apply the brakes, and then air is lost.",
  "combination-vehicles-12": "When the front trailer supports are up and the trailer rests on the tractor, the tractor frame must clear the landing gear. Without that clearance, the landing gear can hit the frame when the trailer is moved.",
  "combination-vehicles-13": "A fully loaded trailer has more weight pushing on the brakes, so it stops in the shortest distance. The extra weight gives the tires more grip on the road.",
  "combination-vehicles-14": "Triple trailers are the most likely to roll over in a turn, because each added trailer raises the load's center of gravity and makes the rig less stable.",
  "combination-vehicles-15": "Before backing under the trailer, supply air to the trailer system and pull out the air supply knob. This is how the trailer brakes are released, so they are ready for the trailer to be moved.",
  "combination-vehicles-16": "Glad hands connect the service and emergency air lines between the tractor and the trailer.",
  "combination-vehicles-17": "To check the air lines and trailer brakes, apply and release the trailer brakes and listen for them. If the sounds match, the lines are not crossed and the brakes work.",
  "combination-vehicles-18": "The hand valve is used to test the trailer brakes. It is not a parking brake, and it is not used in normal driving.",
  "combination-vehicles-19": "Antilock brakes on the trailer help you keep control while braking, because they stop the wheels from locking.",
  "combination-vehicles-20": "Going slow around turns is one way to prevent a rollover, because speed in a turn creates the force that tips the vehicle. Keeping the cargo low is the other way.",
  "combination-vehicles-21": "An empty trailer is the most likely to jackknife, because it has little weight on its drive wheels and can slide easily.",
  "combination-vehicles-22": "You should allow at least one second for each 10 feet of vehicle length, so you have time to stop. That makes the following distance at least 10 seconds for a 100 foot rig.",
  "combination-vehicles-23": "After coupling, raise the landing gear in low gear. Low gear gives the most power to crank it up.",
  "combination-vehicles-24": "Chocks should always be used to park a trailer, so it cannot roll away, whether or not the ground is sloped.",
  "combination-vehicles-25": "The trailer air supply valve is pushed in to supply air to the trailer tanks. Pulling it out cuts off the air.",
  "combination-vehicles-26": "The fifth wheel plate must be greased so it turns freely. If it is dry, the trailer can bind and cause steering problems.",
  "combination-vehicles-27": "Semitrailers made before 1975 often did not have spring brakes. Spring brakes are the emergency brakes that come on when air is lost.",
  "combination-vehicles-28": "When the front trailer supports are up and the trailer rests on the tractor, you must check both the tractor tires and the tractor frame for clearance. Both checks must pass, so both a and b are correct.",
  "combination-vehicles-29": "You may get out of the vehicle while backing only when you are unsure of your path of travel. Then you should check the path on foot before continuing.",
  "combination-vehicles-30": "A 45 foot trailer in a triple combination cheats, or off-tracks, more than shorter trailers. It follows a wider path in a turn.",
  "combination-vehicles-31": "The locking jaws close around the shank of the kingpin. The shank is the part that the jaws hold.",
  "combination-vehicles-32": "Before you back a tractor under a trailer, the whole air system must be at normal pressure. Low pressure means the brakes may not work when you need them.",
  "combination-vehicles-33": "You should never use the hand valve to park a combination vehicle. The hand valve only tests the trailer brakes.",
  "combination-vehicles-34": "Before backing under a trailer, the trailer brakes must be locked. This keeps the trailer from rolling as you back up.",
  "combination-vehicles-35": "Using the hand valve before the brake pedal is not recommended. It can cause the trailer to skid or jackknife, so it should not be done.",
  "combination-vehicles-36": "If the fifth wheel locking lever is not locked after the jaws close, the coupling is not right. It must be fixed before you drive.",
  "combination-vehicles-37": "If the emergency air line breaks, air is lost from the emergency line. That causes the trailer's emergency brakes to come on, which is their safety purpose.",
  "combination-vehicles-38": "After connecting the air lines and before backing under the trailer, supply air to the trailer system and pull out the air supply knob. That releases the trailer brakes.",
  "combination-vehicles-39": "A bobtail tractor, with no trailer, can take longer to stop than a combination vehicle loaded to maximum weight. The loaded rig has more weight on its brakes.",
  "combination-vehicles-40": "If the trailer antilock brakes are not working, you may drive normally but should get the system serviced soon. The regular brakes still work.",
  "combination-vehicles-41": "Air and electrical lines should be secured with enough slack for turns. Lines pulled tight can break when the rig turns.",
  "combination-vehicles-42": "If the yellow ABS malfunction lamp on the left side of the trailer stays on, the trailer ABS brakes are not working properly.",
  "combination-vehicles-43": "The safest way to make a turn without entering another lane is to turn wide as you complete the turn. That keeps the trailer in its own lane.",
  "combination-vehicles-44": "After uncoupling and while you inspect the trailer supports, the tractor transmission should be in neutral. This keeps the tractor from moving.",
  "combination-vehicles-45": "When driving doubles, you close the shut-off valve in the back trailer. That valve is in the last trailer, so it is the one closed.",
  "combination-vehicles-46": "After locking the kingpin into the fifth wheel, check the connection by pulling the tractor ahead gently with the trailer brakes locked. If the trailer stays, the coupling is secure.",
  "combination-vehicles-47": "Dummy couplers or locked glad hands keep dirt and water out of the lines when the trailer is not connected. This protects the air system.",
  "combination-vehicles-48": "Before you back under the trailer, hook up the emergency and service air lines. The electrical cable is connected after the trailer is coupled.",
  "combination-vehicles-49": "After a crash, the first thing to do is turn on the four-way flashers. This warns other drivers that the vehicle has stopped.",
  "combination-vehicles-50": "A major leak in the emergency line makes the tractor protection valve close and the trailer emergency brakes come on. The emergency line controls those brakes.",
  "combination-vehicles-51": "To unlock the fifth wheel, the locking lever is placed in the open position. The jaws then release the kingpin.",
  "combination-vehicles-52": "If both air lines pull apart, the trailer brakes come on, and the tractor protection valve closes. That keeps the tractor from losing all its air.",
  "combination-vehicles-53": "When checking the trailer emergency brakes, the tractor protection control valve is placed in the emergency position. That lets you test the emergency brakes.",
  "combination-vehicles-54": "The emergency line is colored red and the service line is colored blue. These colors help keep the two lines from being mixed up.",
  "combination-vehicles-55": "To unlock the fifth wheel, pull the release handle to the open position. The jaws open and release the kingpin.",
  "combination-vehicles-56": "The trailer air supply control valve closes automatically when air pressure drops to between 20 and 45 psi. That keeps the trailer from being used with low air.",
  "combination-vehicles-57": "To stop a trailer skid, release the service brakes. Braking hard keeps the wheels locked, so releasing them lets the wheels grip again.",
  "combination-vehicles-58": "When backing a tractor under a trailer, always use the lowest reverse gear. That lets you back slowly and control the coupling.",
  "combination-vehicles-59": "After shutting off the trailer air and locking the trailer brakes, back up gently to ease pressure on the fifth wheel jaws. That makes the jaws easier to release.",
  "combination-vehicles-60": "This question has conflicting answers in the study material (see question 76). Check your manual for the correct fifth wheel tilt when coupling.",
  "combination-vehicles-61": "After the trailer is coupled, the tractor protection control valve is placed in the normal position. That lets the trailer brakes work normally.",
  "combination-vehicles-62": "A higher center of gravity makes a vehicle easier to tip over. That is why high loads are more likely to roll in turns.",
  "combination-vehicles-63": "The trailer is at the right height when it is raised slightly as you back under it. Then the kingpin will sit in the fifth wheel jaws.",
  "combination-vehicles-64": "The landing gear should be slightly raised while you check that the trailer is securely coupled. This keeps the landing gear off the ground while the coupling is tested.",
  "combination-vehicles-65": "When you back under a semitrailer, line up directly in front of the trailer. Then the kingpin lines up with the fifth wheel.",
  "combination-vehicles-66": "Keeping the cargo as low as possible is one way to prevent a rollover. The other is going slow around turns.",
  "combination-vehicles-67": "Before driving away, the front trailer supports must be fully raised, with the crank handle secured in its bracket. Landing gear that is down can hit the road.",
  "combination-vehicles-68": "If a trailer has antilock brakes, yellow ABS malfunction lamps are on the left side of the trailer. That is where you check for the ABS indicator.",
  "combination-vehicles-69": "A major leak in the service line lets service air escape. That causes the trailer emergency brakes to come on.",
  "combination-vehicles-70": "With the engine off and brakes on, a combination vehicle should not lose more than 4 psi per minute. More leakage points to a problem.",
  "combination-vehicles-71": "Lower the landing gear until it makes firm contact with the ground, then crank a few extra turns in low gear. That takes some weight off the fifth wheel without lifting the trailer off it. This answer was added from web sources, not the study file.",
  "combination-vehicles-72": "A 45 foot trailer pulled by a 5-axle tractor cheats, or off-tracks, the most, so it follows the widest path in a turn.",
  "combination-vehicles-73": "The safety catch must be over the locking lever for the coupling to be complete. It keeps the lever from opening by itself.",
  "combination-vehicles-74": "If the spring brakes don't release when you push the trailer air supply valve, check the air line connections first. A bad connection keeps air from getting to the trailer.",
  "combination-vehicles-75": "After uncoupling, inspect the landing gear with the tractor frame under the trailer. This lets you see the landing gear that holds the trailer.",
  "combination-vehicles-76": "This question has conflicting answers in the study material (see question 60). Check your manual for the correct fifth wheel tilt when coupling.",
  "general-knowledge-1": "Containerized loads are often moved part of the way by rail or ship, then by truck. The container carries the freight across those legs.",
  "general-knowledge-2": "The hazardous materials endorsement covers chemical knowledge only as it applies to safe handling. Basic chemistry is not required, while loading rules and placards are.",
  "general-knowledge-3": "In a highway work zone, you should adjust your speed to the traffic and conditions, which can mean slowing further than the posted limit in bad weather.",
  "general-knowledge-4": "If you are on a clear shoulder, stay on it and slow to a stop, then move back onto the pavement when it is safe. Braking hard or steering sharply at speed can make the vehicle roll or skid.",
  "general-knowledge-5": "Implied consent means that by driving on public roads, you have already agreed to be tested for alcohol in your blood if police ask.",
  "general-knowledge-6": "You should stop driving whenever you become sleepy. Fatigue can cause a crash at any point in a trip, so hours alone do not decide it.",
  "general-knowledge-7": "All hazardous materials can present a health or safety threat, which is why they are regulated. The other choices wrongly suggest some materials are harmless or that no restrictions apply.",
  "general-knowledge-8": "A first conviction for driving a commercial vehicle under the influence costs the CDL for at least one year.",
  "general-knowledge-9": "Shifting gears correctly keeps the vehicle under control, especially on hills and curves. A wrong gear can cause loss of speed control or a skid.",
  "general-knowledge-10": "During the pre-trip inspection, the ignition key should be kept in your pocket, so no one can start the vehicle while you are checking it.",
  "general-knowledge-11": "Commercial vehicles are often wider than other vehicles, so they need careful lane positioning to keep clear of traffic on both sides.",
  "general-knowledge-12": "You must carry three reflective triangles to warn traffic when the vehicle is stopped on the road.",
  "general-knowledge-13": "When you must cross into the oncoming lane to turn, watch for oncoming traffic before you make the turn. Backing up or stopping in the turn can cause a crash.",
  "general-knowledge-14": "At night you can only see as far as your headlights reach, so you should slow down until your stopping distance fits within what you can see ahead.",
  "general-knowledge-15": "A front tire failure causes steering problems, such as the wheel twisting or being hard to steer. It does not cause the vehicle to fishtail, which is more typical of a rear tire failure.",
  "general-knowledge-16": "The fuel level is not part of the pre-trip inspection, but lights, cargo securement, and other parts are. Checking fuel is not a safety inspection item.",
  "general-knowledge-17": "Without a hazardous materials endorsement, you must refuse to haul placarded hazardous materials. Hauling it anyway violates the rules.",
  "general-knowledge-18": "Blood alcohol concentration depends on body weight, so weight is needed to work it out. Tolerance and age do not change the formula.",
  "general-knowledge-19": "To correct a skid caused by the drive wheels, stop braking, turn quickly, and countersteer. Releasing the brakes lets the wheels regain traction.",
  "general-knowledge-20": "ABS keeps the wheels from locking during braking, so you keep steering control. It does not increase jackknifing or skids.",
  "general-knowledge-21": "When you set out reflective triangles, hold them between yourself and oncoming traffic. That keeps you protected while you place them.",
  "general-knowledge-22": "An escape ramp is for any driver who has lost braking power. It slows the vehicle on a gravel bed so it can stop safely.",
  "general-knowledge-23": "Hydraulic brakes are checked on the vehicle when it is stopped, because they work without air and can fail quietly.",
  "general-knowledge-24": "If hydraulic brakes lose pressure and the pedal goes soft, pumping the pedal can build pressure again. This is the best action to try first.",
  "general-knowledge-25": "After a vehicle fire, get the vehicle off the road and notify emergency services. Trying to fight a fire yourself can put you in danger.",
  "general-knowledge-26": "If you have been drinking, you should wait for the alcohol to wear off. Coffee and cold showers do not lower blood alcohol.",
  "general-knowledge-27": "In cold weather, tires need enough tread depth to give traction for steering and pushing through snow. Tread depth is not doubled in cold weather.",
  "general-knowledge-28": "Using the brakes on a downgrade adds to the braking effect of the engine. Together they keep speed under control.",
  "general-knowledge-29": "On a snow-packed road you should reduce speed by about half to keep the vehicle under control.",
  "general-knowledge-30": "Countersteering means turning the wheel back the other way after steering to avoid a hazard, to bring the vehicle back under control.",
  "general-knowledge-31": "Battery fluid level does not help prevent a vehicle fire. Checking cargo ventilation and electrical insulation does.",
  "general-knowledge-32": "A tire blowout at highway speed causes a vibration you can feel through the steering wheel or seat. A hiss or a rapid drop in speed does not usually happen.",
  "general-knowledge-33": "A broken exhaust system can let poisonous fumes, such as carbon monoxide, into the cab or sleeper berth.",
  "general-knowledge-34": "You should signal continuously while turning so you keep both hands on the wheel. Turning the signal off is not required, and many vehicles do not cancel it automatically.",
  "general-knowledge-35": "At low speed you should look about one block ahead. This gives you time to see and react to hazards.",
  "general-knowledge-36": "On a curved ramp you should keep your speed 5 to 10 mph below the posted limit. That keeps the vehicle from tipping over.",
  "general-knowledge-37": "When faced with an aggressive driver, make every attempt to get out of their way. Avoiding conflict is safer than competing with them.",
  "general-knowledge-38": "Doubling your speed takes about four times the distance to stop. Stopping distance rises much faster than speed.",
  "general-knowledge-39": "On slippery roads, make turns as gently as possible. Sharp turns can cause a skid on low traction.",
  "general-knowledge-40": "Limit horn use because it can startle other drivers. A horn sounded too often can make others react badly.",
  "general-knowledge-41": "Stopping periodically for rest and exercise helps prevent fatigue on a long trip. Stimulants do not replace rest.",
  "general-knowledge-42": "Electric and hydraulic retarders are real types. A robotic retarder is not a type of retarder.",
  "general-knowledge-43": "If you do not keep both hands on the wheel, the wheel can pull out of your hands if it hits a bump or a crosswind.",
  "general-knowledge-44": "You should balance your hours of service with enough sleep to stay alert. The rules limit driving hours, and there is no 1000 hour exemption.",
  "general-knowledge-45": "Aggressive driving is driving in a selfish, bold, or pushy manner, such as tailgating or cutting in. It is not the same as intending harm.",
  "general-knowledge-46": "If the vehicle catches fire while driving, park in an open area away from buildings and trees. Speeding up can spread the fire.",
  "general-knowledge-47": "You should use low beams when an oncoming vehicle is within 500 feet. High beams would blind the other driver.",
  "general-knowledge-48": "You can check the coolant level of a hot engine, but you should never open a hot pressurized radiator cap. Opening it can cause scalding.",
  "general-knowledge-49": "Tiedowns should be used for at least every 10 feet of cargo, so the load cannot shift.",
  "general-knowledge-50": "On an upgrade with a heavy load, shift to a lower gear to keep your speed and engine power up.",
  "general-knowledge-51": "State laws set legal weight limits. A driver is still responsible for not overloading, even if the shipper loaded the cargo.",
  "general-knowledge-52": "When an oncoming driver drifts into your lane, steering to the right is usually the best action. It keeps you away from the head-on path while staying on the road.",
  "general-knowledge-53": "On a hill or curve, place reflective triangles within 500 feet behind you, so drivers can see the vehicle in time.",
  "general-knowledge-54": "Long vehicles need extra space to turn. Turn into the left lane of the street you are turning onto, then move right once traffic is clear.",
  "general-knowledge-55": "Roads are most slippery when rain first starts, because oil and dirt rise to the surface. The road gets less slippery as the rain continues.",
  "general-knowledge-56": "Cargo should be checked to be well secured within the first 50 miles of a trip, and again after that at regular stops.",
  "general-knowledge-57": "When starting up a hill, release the parking brakes as you apply engine power. Applying power first can roll the vehicle back.",
  "general-knowledge-58": "A full stop is required at a railroad crossing when the nature of the cargo makes it mandatory under state or federal rules, such as for many hazardous materials.",
  "general-knowledge-59": "Dual rear tires help prevent fishtailing if one rear tire fails, because the other tire keeps the vehicle stable.",
  "general-knowledge-60": "Retarders can only be used where the law allows them. Local rules set where they may be used.",
  "general-knowledge-61": "A burning tire should be cooled with water, because water cools it and keeps it from spreading.",
  "general-knowledge-62": "Use your horn when it may help avoid a crash, such as warning another driver of your presence. Using it because a car is in your way is not a safe reason.",
  "general-knowledge-63": "With a height over 13 feet, you should stop and make sure the clearance is high enough before going under it. Assuming it is high enough can cause a serious crash.",
  "general-knowledge-64": "When passing a vehicle, pedestrian, or bicycle, assume they may move into your lane, so leave room and be ready to slow.",
  "general-knowledge-65": "Little weight on the drive axle means less traction on the drive wheels, so the vehicle can slip or lose traction.",
  "general-knowledge-66": "You should test the parking brake while the vehicle is parked, by holding the vehicle and checking that it stays stopped.",
  "general-knowledge-67": "You should look ahead 12 to 15 seconds while driving, so you have time to react to hazards.",
  "general-knowledge-68": "A flashing ABS light means the antilock system may not be working properly, so the brakes may not have the extra control. The vehicle should be checked.",
  "general-knowledge-69": "Alcohol goes directly from the stomach into the bloodstream, and a drinker cannot control how fast the body absorbs or removes it. Only the other choice is false.",
  "general-knowledge-70": "Controlled braking is squeezing the brakes firmly without locking the wheels, which keeps steering control while stopping.",
  "general-knowledge-71": "Fog can get thicker as you enter it, so assume it will and slow down accordingly.",
  "general-knowledge-72": "Rust around wheel nuts can mean the nuts are loose, because rust shows movement. Missing lug nuts and mismatched lock rings are unsafe.",
  "general-knowledge-73": "If the headlights do not work properly, you should clean and adjust them. Leaving on high beams can blind other drivers.",
  "general-knowledge-74": "When steering to avoid a crash, do not turn any more than needed to clear the hazard. Extra turning can lead to a rollover or skid.",
  "general-knowledge-75": "In heavy rain or snow, turn on your low-beam headlights so other drivers can see you. Cab lights do not help them see your vehicle.",
  "general-knowledge-76": "On a downhill off-ramp curve, slow down about 5 mph below the posted speed limit. The downhill grade and curve make it unsafe to take the ramp at full speed. Sources disagree on this one, see question 132.",
  "general-knowledge-77": "In heavy fog, park at a rest area or truck stop until it clears. Driving through dense fog is very dangerous.",
  "general-knowledge-78": "On a divided highway, place one triangle within 10 feet of the rear, one about 100 feet back, and one about 200 feet back. This warns traffic in time.",
  "general-knowledge-79": "Brake shoes should not have oil, grease, or brake fluid on them, because these reduce braking power and can cause brake failure.",
  "general-knowledge-80": "The most important thing about emergency braking is that a skidding wheel means you cannot control the vehicle. Keep the wheels from locking.",
  "general-knowledge-81": "A vehicle is put out of service if one-fourth or more of the leaves in any leaf spring are missing, because the spring cannot hold the load safely.",
  "general-knowledge-82": "Give an aggressive driver the benefit of the doubt. Staying calm and avoiding conflict is the safest response.",
  "general-knowledge-83": "Empty trucks take longer to stop than loaded ones in many cases, because light vehicles can have less traction. This is not the same for buses.",
  "general-knowledge-84": "When you see a hazard ahead, use your four-way flashers or brake lights to warn others behind you.",
  "general-knowledge-85": "You should downshift before you enter a curve. Shifting in the curve can upset the vehicle.",
  "general-knowledge-86": "Changing lanes frequently and abruptly without notice is a sign of an aggressive driver. It makes other drivers unable to predict your moves.",
  "general-knowledge-87": "Use mirrors to check where the rear of your vehicle is while making turns, so you do not hit something on the side.",
  "general-knowledge-88": "Tourists may be a hazard because they may drive slowly, make sudden stops, or change lanes without warning, because they are unfamiliar with the road.",
  "general-knowledge-89": "A diamond-shaped hazardous materials label must be on the container. The label shape and color tell handlers the hazard class.",
  "general-knowledge-90": "Fatigue can only be cured by sleep. Willpower and non-sleep aids do not replace rest.",
  "general-knowledge-91": "Rough acceleration can cause mechanical damage to the drive train. Smooth acceleration protects the vehicle.",
  "general-knowledge-92": "If the brake pedal goes to the floor, pumping it may build pressure again, so you can stop the vehicle. The parking brake works on its own system.",
  "general-knowledge-93": "There are two types of jackknife: a trailer jackknife and a tractor jackknife. Both are correct, so the answer is both A and B.",
  "general-knowledge-94": "The bridge formula permits less maximum weight on axles that are close together, because the load concentrates on the bridge.",
  "general-knowledge-95": "If cargo is loaded all to the rear, the drive wheels carry most of the weight while the steering axle is light. That can cause poor traction on the drive wheels.",
  "general-knowledge-96": "A round black on yellow sign means a railroad crossing ahead. Slow down, look and listen, and be prepared to stop if a train is approaching.",
  "general-knowledge-97": "Turn signals and four-way flashers use the same circuit, so they cannot be checked together. Brake lights and turn signals are checked one at a time.",
  "general-knowledge-98": "Perception distance is the distance the vehicle travels from when the eyes see a hazard to when the brain knows it is a hazard.",
  "general-knowledge-99": "You should choose a speed that lets you stop within the distance you can see ahead. That leaves room to react to anything in your path.",
  "general-knowledge-100": "If the brakes fail on a downgrade, first look for another way to slow the vehicle, such as an escape ramp, or use engine braking.",
  "general-knowledge-101": "Drug use can cause accidents and arrest. Some prescription drugs can impair driving, so they cannot be assumed safe.",
  "general-knowledge-102": "A commercial driver is considered intoxicated at a blood alcohol concentration of 0.04, which is lower than the limit for regular drivers.",
  "general-knowledge-103": "Tires of mismatched sizes should not be used on the same vehicle, because the different sizes can cause uneven load and handling problems.",
  "general-knowledge-104": "The tachometer shows engine speed, so you can use it to know when to shift. That is the purpose of the tachometer.",
  "general-knowledge-105": "Short-term and daily rental truck drivers are often not used to the limited vision of a large vehicle, so they can pose a hazard.",
  "general-knowledge-106": "In hot weather, you should check tire mounting and air pressure before driving. Heat raises tire pressure, so checking before the trip shows any real problem.",
  "general-knowledge-107": "When stopped on a one-way or divided highway, place the triangles at 10 feet, 100 feet, and 200 feet toward approaching traffic. This gives drivers warning in time.",
  "general-knowledge-108": "Any detectable amount of alcohol while on duty can put a commercial driver out of service for 24 hours. The standard is zero tolerance for on-duty use.",
  "general-knowledge-109": "Brake shoes should never have brake fluid on them, because it reduces braking power and can cause brake failure. So saying they should have brake fluid is the statement that is NOT true. A missing leaf and a cracked drum are both unsafe and must be fixed.",
  "general-knowledge-110": "Braking in an emergency should keep the vehicle in a straight line, and it does matter how you brake. You should not wait until speed drops to 20 mph before using the brakes.",
  "general-knowledge-111": "After driving through water, gently applying the brakes helps dry them out while keeping control. Hard pressure on both pedals can upset the vehicle.",
  "general-knowledge-112": "A first conviction for driving a commercial vehicle under the influence usually leads to a suspension of the CDL of at least one year.",
  "general-knowledge-113": "At normal highway speed you should look about one quarter mile ahead. That gives time to spot and react to hazards.",
  "general-knowledge-114": "Prescription drugs can be taken while driving only if a doctor confirms they will not affect your driving ability. Amphetamines are not allowed to keep you alert.",
  "general-knowledge-115": "To stay alert, take short breaks before you get drowsy. Waiting until you are drowsy is too late, because fatigue has already set in.",
  "general-knowledge-116": "High beams should be used only when it is safe and legal. They must be dimmed for oncoming traffic and vehicles ahead.",
  "general-knowledge-117": "When looking ahead, look back and forth, near and far. Scanning this way helps you see hazards early and keeps your eyes moving.",
  "general-knowledge-118": "Heavy vehicles need larger gaps in traffic than cars because they take longer to speed up and stop. Count on others to move for you is not safe.",
  "general-knowledge-119": "If you leave the road in an emergency, avoid braking until your speed has dropped to about 20 mph. Braking hard on loose ground can make the vehicle skid or roll.",
  "general-knowledge-120": "When the temperature drops, bridges freeze before roads do, because they have cold air above and below them. Drivers should slow down on bridges first.",
  "general-knowledge-121": "Steering wheel play of more than 10 degrees, about 2 inches on a 20 inch wheel, must be fixed before the vehicle is driven. Too much play makes steering unsafe.",
  "general-knowledge-122": "A distracted driver's vehicle drifts across lane lines and moves at variable speeds. Those signs show the driver is not paying attention.",
  "general-knowledge-123": "Forcing an automatic transmission into a low gear at high speed can damage the transmission. It does not cause loss of steering control.",
  "general-knowledge-124": "Park so you can pull forward when you leave. Backing out of a space can be dangerous in a large vehicle.",
  "general-knowledge-125": "The safest way to use in-vehicle communication equipment is to pull off the road in a safe, legal place. Even hands-free use takes attention from driving.",
  "general-knowledge-126": "On a long, steep downgrade, use the braking effect of the engine first. Relying on brakes alone can overheat them and cause brake fade.",
  "general-knowledge-127": "Hazardous material containers should be marked with diamond-shaped labels four inches on each side. The shape and size of the label show the hazard.",
  "general-knowledge-128": "As blood alcohol concentration goes up, judgment and self-control are affected. Drinkers often do not notice the effect in themselves.",
  "general-knowledge-129": "Cargo should be balanced in the cargo area so the weight is spread evenly over the axles. Uneven loads cause handling and braking problems.",
  "general-knowledge-130": "The weight of cargo can change the height of your vehicle, because a heavier load settles the suspension lower. Check your clearance with the load on.",
  "general-knowledge-131": "Pre-loading favorite music before you drive keeps your attention on the road. Searching for CDs or tapes while driving takes your eyes and hands off the wheel.",
  "general-knowledge-132": "On an off-ramp that curves downhill, slow to a safe speed before the curve, not the posted ramp limit. Sources disagree on this one, see question 76.",
  "general-knowledge-133": "A bobtail tractor, with no trailer, has the longest stopping distance because it has less weight on its drive wheels. Less weight means less braking grip.",
  "general-knowledge-134": "For a left turn from two left turn lanes, the outside lane (second from the left) is used by long vehicles. It lets the vehicle make its wide turn safely.",
  "general-knowledge-135": "To return to the road from the shoulder, use your mirrors and turn signals and turn sharply back when it is safe. Riding the shoulder can damage the vehicle.",
  "general-knowledge-136": "Shipping papers for hazardous materials must be kept in a pouch on the driver's door or on the seat, where they can be reached quickly.",
  "general-knowledge-137": "Brake adjustment should be checked often, because brakes can get out of adjustment a lot. Relying on other brakes to make up for poor adjustment is unsafe.",
  "general-knowledge-138": "Signaling other drivers when it is safe to pass you is not a good rule. Heavy vehicles should stay right, and four-way flashers are used only where legal.",
  "general-knowledge-139": "A straight vehicle in a front-wheel skid goes straight ahead even when the steering wheel is turned, because the front wheels have no grip to steer with.",
  "general-knowledge-140": "Water can be used to put out tire fires. Gasoline and electrical fires need other methods, because water can spread or conduct electricity.",
  "general-knowledge-141": "Going onto a shoulder is less dangerous than a collision. Shoulders can be weak or gravelly, so you may have trouble returning to the road.",
  "general-knowledge-142": "A good sign that ice is forming is ice on your outside mirrors. If you see ice on them, slow down and watch for ice on the road.",
  "general-knowledge-143": "To turn quickly in an emergency, you must have a firm grip on the steering wheel. A loose grip can let the wheel slip when you need it most.",
  "general-knowledge-144": "When leaving a tunnel, there may be strong winds. Keep a firm grip on the wheel as you exit.",
  "general-knowledge-145": "Rough acceleration can damage the mechanical parts and the coupling. It does not usually damage tires.",
  "general-knowledge-146": "You can get hung up on railroad tracks if the approach is steep, because the vehicle's underside can rest on the tracks. Check the crossing before you cross.",
  "general-knowledge-147": "Brake drums or discs must not have cracks longer than one-half the width of the friction area. A longer crack makes the drum unsafe.",
  "general-knowledge-148": "Wear your seat belt at all times in a moving vehicle, not only on highways or while driving. It protects you in any crash.",
  "general-knowledge-149": "Laws and restrictions for trucks and buses can vary from place to place. Drivers must check the rules for each area they drive through.",
  "general-knowledge-150": "Backing a heavy vehicle should not be done slowly until you bump the dock. That is unsafe, and you should use a helper and signals instead.",
  "general-knowledge-151": "On a mountain grade, the weight of the vehicle is the most important factor in choosing speed and gear. Heavier loads need more braking and lower gears.",
  "general-knowledge-152": "You should avoid backing whenever you can, because backing is one of the most dangerous maneuvers for a large vehicle.",
  "general-knowledge-153": "You should lightly apply your brakes to flash the brake lights when you are about to exit the road and need to slow down. The flash warns the driver behind you.",
  "general-knowledge-154": "On a road slick with glare ice, stop driving as soon as you can do so safely. Ice is very dangerous and can cause loss of control.",
  "general-knowledge-155": "If you double your speed, stopping distance increases about four times. The distance grows faster than the speed does.",
  "general-knowledge-156": "Alcohol first affects judgment and self-control, which are necessary for safe driving. Even small amounts can start to affect these.",
  "general-knowledge-157": "You should leave one second for each 10 feet of vehicle length as your following distance on a highway. This gives you enough time to stop.",
  "general-knowledge-158": "When heavy traffic moves at 35 mph, the safest speed is about 35 mph. Matching the traffic keeps you from being a hazard.",
  "general-knowledge-159": "A yellow ABS malfunction lamp that lights while driving means the ABS may not be functioning, so the brakes will not have anti-lock protection.",
  "general-knowledge-160": "For a 40-foot vehicle at 35 mph on a dry road with good visibility, keep about 4 seconds of space in front. This gives enough time to stop.",
  "general-knowledge-161": "Mirrors should be adjusted to show some part of the vehicle, so you can see the lane beside you and what is behind you.",
  "general-knowledge-162": "Driving too fast is the primary cause of fatal crashes. Speed reduces the time you have to react and increases the damage of a crash.",
  "general-knowledge-163": "A conviction for driving a commercial vehicle under the influence costs the CDL for at least one year. A second conviction costs it for longer.",
  "general-knowledge-164": "Optional safety equipment can include tire changing equipment, which helps you handle a flat tire on the road.",
  "general-knowledge-165": "Turning on your high beams before a pass is not a suggestion. High beams can blind the driver you are passing.",
  "general-knowledge-166": "Defensive driving means watching for and preparing for hazards before they happen. It is the safest way to drive.",
  "general-knowledge-167": "Poor trailer ventilation can let cargo overheat and catch fire. Good ventilation helps prevent cargo fires.",
  "general-knowledge-168": "Tire tread type does not affect your choice of gear on a grade. The weight of the load and the length of the grade do.",
  "general-knowledge-169": "A brush does not help clear ice from a windshield well. A scraper and the defroster are used to remove it.",
  "general-knowledge-170": "When you cannot see a car in the mirror, wait to change lanes until you are sure it is not in your blind spot. Easing over can put you in its path.",
  "general-knowledge-171": "If a hill or curve keeps drivers from seeing the vehicle within 500 feet, the rear reflective triangle should be moved farther down the road to warn them in time.",
  "general-knowledge-172": "If the antilock brake system is not working, you may drive normally but should get it serviced soon. The regular brakes still work.",
  "general-knowledge-173": "If you have a phone or CB radio, notify authorities before you leave your vehicle. That gets help on the way sooner.",
  "general-knowledge-174": "On a steep downhill grade, use light, steady pressure on the brakes. Strong pressure can overheat the brakes and cause fade.",
  "general-knowledge-175": "When starting a bus on a level surface with good traction, the parking brake is not needed. It is used only for holding the vehicle when parked.",
  "general-knowledge-176": "If the drive wheels spin when you start moving, take your foot off the accelerator. That lets the wheels regain grip.",
  "general-knowledge-177": "When you turn on the ignition, the yellow ABS malfunction lamps light up on the instrument panel. That shows the vehicle has ABS.",
  "general-knowledge-178": "The speed you drive should be set by your visibility. When you cannot see far ahead, you must slow down.",
  "general-knowledge-179": "On an uphill grade, use the parking brake to hold the vehicle until the clutch engages. Then release the parking brake as you apply power.",
  "general-knowledge-180": "A hazard is any road condition or other road user that is a possible danger. You must watch for hazards to avoid them.",
  "general-knowledge-181": "Ice should be removed from the radiator shutters in winter, so the engine can get proper airflow. Frozen shutters can make the engine overheat.",
  "general-knowledge-182": "Most skids are caused by going too fast or trying to stop too quickly. Slowing down and braking gently prevent most skids.",
  "general-knowledge-183": "If wet brakes are applied in heavy rain, the trailer can jackknife. Water on the brakes reduces their grip unevenly.",
  "general-knowledge-184": "A high center of gravity makes a vehicle more likely to tip over on curves. Keep loads low and balanced.",
  "general-knowledge-185": "Brake fade can be caused by the brakes getting very hot. Overheated linings lose their friction.",
  "general-knowledge-186": "Controlled braking is used to keep a vehicle in a straight line when braking. It means braking firmly without locking the wheels.",
  "general-knowledge-187": "Windshield washer antifreeze should be used in cold weather, so the washer fluid does not freeze on the windshield.",
  "general-knowledge-188": "Backing a commercial vehicle is always dangerous. Its size and blind spots make backing risky even with a helper.",
  "general-knowledge-189": "When the road is slippery, it takes longer to stop and it is harder to turn without skidding. Drivers need to slow down.",
  "general-knowledge-190": "If your brakes fail on a hill, get off the road as soon as possible. Use an escape ramp or a safe place to slow the vehicle.",
  "general-knowledge-191": "Communication means letting other motorists know your intentions, such as with signals. It is not about talking to police or using a CB.",
  "general-knowledge-192": "The brake pressure you need to stop depends on the vehicle's speed and how quickly you want to stop. Faster speeds and quicker stops need more pressure.",
  "general-knowledge-193": "Keeping an injured person cool is not a good rule. Injured people should be kept warm and comfortable, and not moved unless danger requires it.",
  "general-knowledge-194": "Engine braking is greatest when the engine is near its governed RPM and the transmission is in a lower gear. That gives the most drag.",
  "general-knowledge-195": "Federal inspectors can put a truck or bus out of service if it is unsafe. Safety inspections are part of the enforcement of federal rules.",
  "general-knowledge-196": "Enough engine oil keeps the engine cool in hot weather. Oil lubricates and carries heat away from moving parts.",
  "general-knowledge-197": "Before driving in mountains, know where the escape ramps are on your route. They give you a place to stop if the brakes fail.",
  "general-knowledge-198": "Unstable loads, such as hanging meat or livestock, can shift on curves. They require extra caution.",
  "general-knowledge-199": "Before driving in winter weather, check that the heater is working properly. A heater that fails can leave you cold and unable to see.",
  "general-knowledge-200": "ABS uses sensors and computers to sense potential wheel lock-up. It then reduces brake pressure on the wheel that is about to lock.",
  "general-knowledge-201": "Starting the left turn from the inside lane and swinging right as you turn is not recommended. Turn from the correct lane without swinging into the other lane.",
  "general-knowledge-202": "ABS changes the way you brake in an emergency. It does not let you drive faster or less carefully.",
  "general-knowledge-203": "On a dry road with good visibility, keep at least 5 seconds of space in front of your vehicle. This gives time to stop.",
  "general-knowledge-204": "If ice builds up on your wipers and they no longer clean the windshield, stop safely and fix the problem. You cannot see well enough to drive.",
  "general-knowledge-205": "Emergency braking means responding to a hazard by slowing the vehicle. It is not the same as pushing the brake pedal as hard as possible.",
  "general-knowledge-206": "When a tailgater is behind you in bad weather, increase your following distance. This gives you room to stop safely.",
  "general-knowledge-207": "You need at least 4/32 inch tread depth in every major groove of your front tires. Less tread reduces grip on wet roads.",
  "general-knowledge-208": "The heavier the vehicle or the faster it moves, the more heat the brakes must absorb to stop it. That heat can cause brake fade.",
  "general-knowledge-209": "Retarders can cause the drive wheels to skid when traction is poor. Use them carefully on slippery roads.",
  "general-knowledge-210": "Tire chains should always be carried when driving in winter weather. Chains are needed when roads are icy or snowy.",
  "general-knowledge-211": "The space in front of your vehicle is the most important to manage, because you are driving toward it. Keeping room ahead gives you time to stop.",
  "general-knowledge-212": "On a hot day, asphalt softens and bleeds oil to the surface, which makes the road slippery. Slow down in hot weather.",
  "general-knowledge-213": "You should signal early and change lanes slowly and smoothly. That warns others and gives them time to respond.",
  "general-knowledge-214": "Hold the steering wheel with both hands on opposite sides of the wheel. That gives you the most control if the wheel kicks.",
  "general-knowledge-215": "In very hot weather, you should inspect tires every two hours or every 100 miles. Heat can cause tire failure, so frequent checks are needed.",
  "general-knowledge-216": "A helper should be used whenever you have to back. A helper can see the blind spots and guide you safely.",
  "general-knowledge-217": "Front steering tires need at least 4/32 inch tread depth. Less tread reduces grip and increases the risk of a skid.",
  "general-knowledge-218": "Mirrors cannot show every blind spot, so you must check your blind spots by looking over your shoulder or by other means.",
  "general-knowledge-219": "You must inspect the vehicle within the first 50 miles of the trip. Checking early finds problems before they become dangerous.",
  "general-knowledge-220": "Doubling your speed gives your vehicle about four times the destructive power if it crashes. The energy grows with the square of the speed.",
  "general-knowledge-221": "If you must cross into the oncoming lane to turn, watch for oncoming traffic before you move. Stopping in the oncoming lane is dangerous.",
  "general-knowledge-222": "Warning devices for a parked vehicle, such as reflective triangles, should always be carried. They warn other drivers when the vehicle is stopped.",
  "general-knowledge-223": "Before crossing a bridge on a two-lane road, check the weight limit posted for it. A heavy vehicle can damage or fall through a weak bridge.",
  "general-knowledge-224": "When exiting a tunnel, there may be crosswinds that push the vehicle. Keep a firm grip on the wheel.",
  "general-knowledge-225": "Crossing railroad tracks on a dirt road can leave a vehicle hung up halfway across, because the dirt can make the crossing high.",
  "general-knowledge-226": "You should adjust your mirrors before starting the trip. Adjusting them while driving takes your attention away from the road.",
  "general-knowledge-227": "When your vehicle hydroplanes, release the accelerator. Letting the speed drop lets the tires regain contact with the road.",
  "general-knowledge-228": "If a car cuts in front of you, do not honk and stay close behind it. Stay back and slow down, or signal and change lanes if it is safe.",
  "general-knowledge-229": "If you are not sure you have enough overhead clearance, find another route that does not need you to drive under the object.",
  "general-knowledge-230": "When hydraulic brakes are working properly, the pedal should not move under steady pressure. Movement shows a leak or a fault.",
  "general-knowledge-231": "Overweight or oversized loads can only be driven in daylight. The restriction keeps the load easier to see.",
  "general-knowledge-232": "The most important reason to inspect your truck or bus is safety. Inspections find problems that can cause crashes.",
  "general-knowledge-233": "If your vehicle gets stuck on a railroad crossing, get out and move away from the tracks. A train can strike the vehicle at any time.",
  "general-knowledge-234": "Off-tracking is the swing a long vehicle makes on turns, as the rear wheels follow a path inside the front wheels.",
  "general-knowledge-235": "To stay alert on a long trip, stop periodically for rest and exercise. Stimulants and a warm, closed cab do not fix fatigue.",
  "general-knowledge-236": "Many cold medicines cause drowsiness, so they should not be used while driving. Check the label for warnings.",
  "general-knowledge-237": "If you are not sure what to use on a hazardous material fire, wait for qualified firefighters. Water or dirt may make the fire worse.",
  "general-knowledge-238": "Antilock braking is an addition to your normal brakes, not a replacement for them. It helps keep the wheels from locking.",
  "general-knowledge-239": "You should learn how a fire extinguisher works before a fire happens. In a fire there is no time to read the instructions.",
  "general-knowledge-240": "Without a hazardous materials endorsement, you can drive a vehicle hauling hazardous materials when the vehicle does not require placards. Placarded loads require the endorsement.",
  "general-knowledge-241": "At 55 mph, the total stopping distance is about the length of a football field. That includes reaction and braking distance.",
  "general-knowledge-242": "Hydroplaning is more likely when tire pressure is low, because low pressure lets the tire ride on water more easily.",
  "general-knowledge-243": "Retarders help slow the vehicle while driving and reduce brake wear. They take load off the service brakes on long downgrades.",
  "general-knowledge-244": "Vibration can be a sign of tire failure. A tire that is failing can vibrate or thump while you drive.",
  "general-knowledge-245": "Stab braking should not be used on a vehicle with antilock brakes, because the ABS does this job automatically.",
  "general-knowledge-246": "Placards must be placed on all four sides of a vehicle carrying hazardous materials that require them. The placards warn others on every side.",
  "general-knowledge-247": "Cargo blocking is placed at the front, back, and/or sides of the cargo to keep it from moving.",
  "general-knowledge-248": "A double with empty trailers has the least weight to hold it in the lane, so strong winds push it the most.",
  "general-knowledge-249": "Never remove the radiator cap on a pressurized system until the system has cooled. Hot coolant can spray out and cause serious burns.",
  "general-knowledge-250": "In work zones, watch for sharp pavement drop-offs, because they can cause a vehicle to lose control.",
  "general-knowledge-251": "To correct a rear-wheel acceleration skid, stop accelerating. Removing power lets the wheels regain traction.",
  "general-knowledge-252": "Wind is especially a problem when coming out of tunnels, because the wind can hit the side of the vehicle suddenly.",
  "general-knowledge-253": "Total stopping distance is perception distance plus reaction distance plus braking distance. Each part adds to the total.",
  "general-knowledge-254": "If you must use a cell phone while driving, pull off the road into a safe and legal position. Talking while driving takes attention away from the road.",
  "general-knowledge-255": "On a vehicle with a trailer, the trailer can push the towing vehicle sideways in a rear wheel skid. This is why skids are dangerous with trailers.",
  "general-knowledge-256": "Many heavy vehicle accidents happen between midnight and 6 a.m., when drivers are most tired. Plan rest breaks for those hours.",
  "general-knowledge-257": "Air pressure in a tire increases as the tire gets hotter, so pressure changes with temperature. Checking pressure before the trip, and watching it during a trip, shows whether a tire is losing air.",
  "general-knowledge-258": "The weight of a vehicle changes its height, because heavy loads settle the suspension. Check clearance with the load on.",
  "general-knowledge-259": "Mirrors should show some part of the vehicle, so you can see the lane and what is beside you. You cannot see your entire vehicle in a mirror.",
  "general-knowledge-260": "A BAC of 0.02 at a roadside stop means the driver is placed out of service for 24 hours. Even low levels carry that consequence.",
  "general-knowledge-261": "A vehicle's speed naturally increases on a downgrade because of gravity. Brakes and engine braking are needed to control speed.",
  "general-knowledge-262": "When truck speed limits are less than car limits, be extra careful when changing lanes. Cars and trucks move at different speeds, so lane changes need extra care.",
  "general-knowledge-263": "When turning right with a long vehicle, swing wide as you complete the turn. Swinging wide before the turn can take the trailer into the wrong lane.",
  "general-knowledge-264": "To prevent brake fade, select a gear that keeps your vehicle at a safe speed on the downgrade. The engine then does most of the braking.",
  "general-knowledge-265": "It is unsafe to operate a vehicle with one-fourth of the spring leaves cracked, broken, or missing in any leaf spring.",
  "general-knowledge-266": "Turn on your four-way emergency flashers when you park on the side of the road. They warn other drivers that the vehicle is stopped.",
  "general-knowledge-267": "Gross combination weight is the total weight of the powered unit, the trailer, and the cargo.",
  "general-knowledge-268": "A red triangle with an orange center marks a slow-moving vehicle. It warns drivers to slow down.",
  "general-knowledge-269": "Sleep is the only thing that can overcome fatigue. Coffee and short breaks help for a while, but only sleep fully cures it.",
  "general-knowledge-270": "Hydraulic brake cylinder leaks are not part of the air brake walk-around check. Brake adjustment and hoses are checked.",
  "general-knowledge-271": "Axle mounts should be checked at each point where they are secured to the vehicle frame and axle. Loose mounts can cause the suspension to fail.",
  "general-knowledge-272": "Flashing the brake light to get someone off your tail is not a proper use of the lights. Brake lights should show your slowing, not be used to pressure others.",
  "general-knowledge-273": "At night, keep your speed slow enough that you can stop within the range of your headlights. You cannot stop for a hazard you cannot see.",
  "general-knowledge-274": "When a light has been green for a long time, start slowing down so you are ready to stop. It may change any time.",
  "general-knowledge-275": "After starting the engine, the coolant temperature gauge should begin a gradual rise to normal. The oil pressure should rise right away, not in several minutes.",
  "general-knowledge-276": "State inspectors can inspect your truck or bus and put it out of service if it is unsafe. Inspections are a normal part of enforcement.",
  "general-knowledge-277": "If someone is tailgating you, increase your following distance. That gives you room to stop without a crash.",
  "general-knowledge-278": "If you need to tilt the cab, secure loose things so they do not fall and break anything. Loose items can cause damage and injury.",
  "general-knowledge-279": "Cargo should be inspected after every break you take while driving. Loads can shift, so checking them keeps the cargo secure.",
  "general-knowledge-280": "If you must return to the road before stopping on the shoulder, use your mirrors and turn signals and turn sharply back when it is safe.",
  "general-knowledge-281": "Valve clearance is not part of the pre-trip engine compartment check. Oil level and worn wiring insulation are checked.",
  "general-knowledge-282": "If a car keeps its high beams on at night, look to the right lane or the edge markings of the road. Looking into the glare makes you lose your way.",
  "general-knowledge-283": "When parked at the side of the road at night, turn on your four-way emergency flashers to warn others.",
  "general-knowledge-284": "On a slippery road, slow down gradually. Sudden slowing or braking can cause a skid.",
  "general-knowledge-285": "If brakes overheat and fail on a long downhill, downshift and look for an escape ramp or route. Both actions help stop the vehicle.",
  "general-knowledge-286": "On a slippery road in rain, decrease your speed even further for the conditions. Wet roads need slower speeds.",
  "general-knowledge-287": "In a traffic emergency, you can often turn to miss an obstacle more quickly than you can stop. Stopping is not always the safest choice.",
  "general-knowledge-288": "Most serious skids result from driving too fast for the conditions. Speed reduces the grip and the time to react.",
  "general-knowledge-289": "Dry bulk tanks require special care because the load can shift. A shifting load can change the balance and the braking.",
  "general-knowledge-290": "A triple with 45 foot trailers has the most chance to off-track in turns. The long trailers follow a wider path than shorter ones.",
  "general-knowledge-291": "In steady rain, a good sign that hydroplaning can occur is when the vehicle in front throws up water splashes. Water on the road is causing the spray.",
  "general-knowledge-292": "Exhaust should receive extra attention during a winter weather inspection. Leaks can let poisonous fumes into the cab.",
  "general-knowledge-293": "When a tire blows out, first stay off the brake until the vehicle slows down. Sudden braking can make the vehicle lose control.",
  "general-knowledge-294": "Truck escape ramps help avoid damage to vehicles and drivers when brakes fail. They slow the vehicle safely.",
  "general-knowledge-295": "Merging is safest when you wait for a large enough gap in traffic to enter the road. Forcing your way in is dangerous.",
  "general-knowledge-296": "When going down a long steep grade in a manual transmission truck, use a lower gear than you would use to climb the hill. The engine then holds the speed down.",
  "general-knowledge-297": "You recognize hazardous materials by the label on the container. Labels show the hazard class.",
  "general-knowledge-298": "Turn signals should be used at least 100 feet before turning or changing lanes. That warns drivers behind you in time.",
  "general-knowledge-299": "On a dark road with few streetlights, use your high beams when it is legal and keep the interior lights off. That gives you the best view ahead.",
  "general-knowledge-300": "Based on your vehicle and its cargo, select a safe speed that is within the posted speed. Heavy loads need slower speeds on grades.",
  "general-knowledge-301": "If you have no CB radio, the first thing to do at an accident scene is protect the area. Warning other traffic prevents a second crash.",
  "general-knowledge-302": "Battery chargers are optional equipment that can be carried in a vehicle. Fire extinguishers and warning devices are required equipment.",
  "general-knowledge-303": "When turning, signal early so drivers behind you know what you intend to do. Early signaling gives them time to react.",
  "general-knowledge-304": "Convex mirrors show a wider area than flat mirrors, but objects look farther away than they are. That is why convex mirrors need care.",
  "general-knowledge-305": "Automatic transmissions do not provide extra gears on trucks. Auxiliary transmissions and multi-speed rear axles do.",
};
